---
abstract: 'Calculate the probability of a protein to be soluble using the Wilkinson-Harrison model'
author:
  - 'Bruno Vecchi <vecchi.b gmail.com>'
generated_by: 'Dist::Zilla version 1.093290'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Tools-Solubility-Wilkinson
requires:
  Carp: 0
  Sub::Exporter: 0
  Test::Exception: 0
  Test::More: 0.88
  constant: 1.03
resources:
  repository: http://github.com/brunoV/bio-tools-solubility-wilkinson/
version: 0.093360
